# Generated by Django 3.0 on 2019-12-17 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examinee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ExamineeExam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('examinee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examinees.Examinee')),
            ],
        ),
    ]
