# Generated by Django 3.0 on 2019-12-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examineeexam',
            name='exam_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='examineeexam',
            name='question_id',
            field=models.IntegerField(default=None),
        ),
    ]
