# Generated by Django 3.0 on 2019-12-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinees', '0002_auto_20191218_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='examineeexam',
            name='answer_id',
            field=models.IntegerField(default=None),
        ),
    ]
