# Generated by Django 3.0 on 2019-12-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('number_of_question', models.IntegerField()),
                ('time_duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ExamQuestionTopic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_id', models.IntegerField()),
                ('question_id', models.IntegerField()),
                ('topic_id', models.IntegerField()),
            ],
        ),
    ]
