# Generated by Django 3.0 on 2019-12-17 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_auto_20191218_0205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examquestiontopic',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='examquestiontopic',
            old_name='topic_id',
            new_name='topic',
        ),
    ]
