# Generated by Django 3.0 on 2019-12-17 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_auto_20191218_0206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examquestiontopic',
            old_name='exam_id',
            new_name='exam',
        ),
    ]
